### ISSUE TITLE
io.js support

### ISSUE THREAD

**Issue by lloydwatkin** [bnoordhuis/node-iconv#106]
I'm looking to update `node-expat` with io.js support but this dependency is failing. Its been suggested for node-expat that it just requires an update of `nan` to >=1.5.

See https://github.com/node-xmpp/node-expat/issues/106

```
lloyd@zenbook:~/Dropbox/code/node-xmpp/node-expat$ npm i --save iconv
-
> iconv@2.1.4 install /home/lloyd/Dropbox/code/node-xmpp/node-expat/node_modules/iconv
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/home/lloyd/Dropbox/code/node-xmpp/node-expat/node_modules/iconv/build'
  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
  AR(target) Release/obj.target/iconv.a
  COPY Release/iconv.a
  CXX(target) Release/obj.target/iconv/src/binding.o
In file included from ../src/binding.cc:18:0:
../node_modules/nan/nan.h:616:19: error: ‘NanNew’ declared as an ‘inline’ variable
       v8::String::ExternalAsciiStringResource *resource) {
                   ^
../node_modules/nan/nan.h:616:19: warning: ‘always_inline’ attribute ignored [-Wattributes]
../node_modules/nan/nan.h:616:19: error: ‘v8::Local<v8::String> NanNew’ redeclared as different kind of symbol
../node_modules/nan/nan.h:610:36: note: previous declaration ‘v8::Local<v8::String> NanNew(v8::String::ExternalStringResource*)’
   NAN_INLINE v8::Local<v8::String> NanNew(
                                    ^
../node_modules/nan/nan.h:616:7: error: ‘ExternalAsciiStringResource’ is not a member of ‘v8::String’
       v8::String::ExternalAsciiStringResource *resource) {
       ^
../node_modules/nan/nan.h:616:48: error: ‘resource’ was not declared in this scope
       v8::String::ExternalAsciiStringResource *resource) {
                                                ^
../node_modules/nan/nan.h: In function ‘bool _NanGetExternalParts(v8::Handle<v8::Value>, const char**, size_t*)’:
../node_modules/nan/nan.h:1973:12: error: ‘class v8::String’ has no member named ‘IsExternalAscii’
   if (str->IsExternalAscii()) {
            ^
../node_modules/nan/nan.h:1974:23: error: ‘ExternalAsciiStringResource’ in ‘class v8::String’ does not name a type
     const v8::String::ExternalAsciiStringResource* ext;
                       ^
../node_modules/nan/nan.h:1975:5: error: ‘ext’ was not declared in this scope
     ext = str->GetExternalAsciiStringResource();
     ^
../node_modules/nan/nan.h:1975:16: error: ‘class v8::String’ has no member named ‘GetExternalAsciiStringResource’
     ext = str->GetExternalAsciiStringResource();
                ^
iconv.target.mk:101: recipe for target 'Release/obj.target/iconv/src/binding.o' failed
make: *** [Release/obj.target/iconv/src/binding.o] Error 1
make: Leaving directory '/home/lloyd/Dropbox/code/node-xmpp/node-expat/node_modules/iconv/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/sbin/versions/io.js/v1.0.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1038:12)
gyp ERR! System Linux 3.13.0-37-generic
gyp ERR! command "node" "/usr/sbin/versions/io.js/v1.0.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/lloyd/Dropbox/code/node-xmpp/node-expat/node_modules/iconv
gyp ERR! node -v v1.0.3
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.13.0-37-generic
npm ERR! argv "/usr/sbin/versions/io.js/v1.0.3/bin/iojs" "/usr/sbin/versions/io.js/v1.0.3/bin/npm" "i" "--save" "iconv"
npm ERR! node v1.0.3
npm ERR! npm  v2.2.0
npm ERR! code ELIFECYCLE

npm ERR! iconv@2.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iconv@2.1.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lloyd/Dropbox/code/node-xmpp/node-expat/npm-debug.log
lloyd@zenbook:~/Dropbox/code/node-xmpp/node-expat$ 
```

**Comment by lloydwatkin** [comment]
Here's a log using latest `nan` and then `npm i .`:

```
lloyd@zenbook:~/Dropbox/code/node-xmpp/node-iconv$ npm i .
-
> iconv@2.1.4 install /home/lloyd/Dropbox/code/node-xmpp/node-iconv
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/home/lloyd/Dropbox/code/node-xmpp/node-iconv/build'
  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
  AR(target) Release/obj.target/iconv.a
  COPY Release/iconv.a
  CXX(target) Release/obj.target/iconv/src/binding.o
In file included from ../node_modules/nan/nan.h:63:0,
                 from ../src/binding.cc:18:
../node_modules/nan/nan_new.h: In instantiation of ‘typename NanIntern::Factory<T>::return_t NanNew(A0) [with T = v8::Integer; A0 = long unsigned int; typename NanIntern::Factory<T>::return_t = v8::Local<v8::Integer>]’:
../src/binding.cc:122:46:   required from here
../node_modules/nan/nan_new.h:184:41: error: call of overloaded ‘New(long unsigned int&)’ is ambiguous
   return NanIntern::Factory<T>::New(arg0);
                                         ^
../node_modules/nan/nan_new.h:184:41: note: candidates are:
In file included from ../node_modules/nan/nan_new.h:165:0,
                 from ../node_modules/nan/nan.h:63,
                 from ../src/binding.cc:18:
../node_modules/nan/nan_implementation_12_inl.h:88:1: note: static NanIntern::IntegerFactory<T>::return_t NanIntern::IntegerFactory<T>::New(int32_t) [with T = v8::Integer; NanIntern::IntegerFactory<T>::return_t = v8::Local<v8::Integer>; int32_t = int]
 IntegerFactory<T>::New(int32_t value) {
 ^
In file included from ../node_modules/nan/nan.h:63:0,
                 from ../src/binding.cc:18:
../node_modules/nan/nan_new.h:87:26: note: static NanIntern::IntegerFactory<T>::return_t NanIntern::IntegerFactory<T>::New(uint32_t) [with T = v8::Integer; NanIntern::IntegerFactory<T>::return_t = v8::Local<v8::Integer>; uint32_t = unsigned int]
   static inline return_t New(uint32_t value);
                          ^
In file included from ../node_modules/nan/nan.h:63:0,
                 from ../src/binding.cc:18:
../node_modules/nan/nan_new.h: In function ‘typename NanIntern::Factory<T>::return_t NanNew(A0) [with T = v8::Integer; A0 = long unsigned int; typename NanIntern::Factory<T>::return_t = v8::Local<v8::Integer>]’:
../node_modules/nan/nan_new.h:185:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
iconv.target.mk:101: recipe for target 'Release/obj.target/iconv/src/binding.o' failed
make: *** [Release/obj.target/iconv/src/binding.o] Error 1
make: Leaving directory '/home/lloyd/Dropbox/code/node-xmpp/node-iconv/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/sbin/versions/io.js/v1.0.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1038:12)
gyp ERR! System Linux 3.13.0-37-generic
gyp ERR! command "node" "/usr/sbin/versions/io.js/v1.0.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/lloyd/Dropbox/code/node-xmpp/node-iconv
gyp ERR! node -v v1.0.3
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

npm ERR! Linux 3.13.0-37-generic
npm ERR! argv "/usr/sbin/versions/io.js/v1.0.3/bin/iojs" "/usr/sbin/versions/io.js/v1.0.3/bin/npm" "i" "."
npm ERR! node v1.0.3
npm ERR! npm  v2.2.0
npm ERR! code ELIFECYCLE
npm ERR! iconv@2.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iconv@2.1.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lloyd/Dropbox/code/node-xmpp/node-iconv/npm-debug.log
lloyd@zenbook:~/Dropbox/code/node-xmpp/node-iconv$ 
```

**Comment by bnoordhuis** [comment]
Mea culpa, fixed in 08e13c9 and released as v2.1.5.

I upgraded most of my modules but I forgot about node-iconv.  Doubly embarrassing because I work on both io.js and nan.

**Comment by lloydwatkin** [comment]
I won't say a word :+1: Thanks

**Comment by rambo-panda** [comment]
+1
