### ISSUE TITLE
iconv error node-gyp rebuild windows 8.1 64bits

### ISSUE THREAD

**Issue by bl0zis** [bnoordhuis/node-iconv#107]
Hello, 
I know this problem has been raised several times, but I tried for several hours searching on the internet for solutions to solve this problem and I could not solve....

Error:

```
C:\Users\Ivan\Desktop\site>npm install iconv --msvs_version=2012

npm WARN package.json http@0.0.0 http is also the name of a node core module.
npm WARN package.json http@0.0.0 No description
npm WARN package.json http@0.0.0 No repository field.
npm WARN package.json http@0.0.0 No README data
\
> iconv@2.1.5 install C:\Users\Ivan\Desktop\site\node_modules\iconv
> node-gyp rebuild


C:\Users\Ivan\Desktop\site\node_modules\iconv>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at errnoException (child_process.js:1001:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:792:34)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Ivan\Desktop\site\node_modules\iconv
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! iconv@2.1.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.1.5 install script.
npm ERR! This is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "iconv" "--msvs_version=2012"
npm ERR! cwd C:\Users\Ivan\Desktop\site
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

```

*node-gyp configure build* work well (i think..)

```
C:\Users\Ivan\Desktop\site>node-gyp configure build
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.10.33 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\Ivan\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Ivan\\Desktop\\site\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Ivan\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi', gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Ivan\\.node-gyp\\0.10.33\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Ivan\\.node-gyp\\0.10.33',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Ivan\\Desktop\\site',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\Ivan\\Desktop\\site\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Построение проектов в этом решении по одному. Чтобы включить параллельное построение, добавьте параметр "/m".
  ╤ючфрэшх ъюфр
  ╤ючфрэшх ъюфр чртхЁ°хэю
  binding.vcxproj -> C:\Users\Ivan\Desktop\site\build\Release\\binding.node
gyp info ok

```
, só I don't know where is the problem...

**Comment by bnoordhuis** [comment]
I suspect that in the first case, node-gyp can't find or execute the python executable.  You can probably find the actual error in npm-debug.log.

**Comment by bl0zis** [comment]
@bnoordhuis you are absolutely right, that was my problem
this helped:
```
npm config set python python2.7
```

Thanks you a lot!
