### ISSUE TITLE
Error building on Amazon Linux

### ISSUE THREAD

**Issue by euvl** [bnoordhuis/node-iconv#112]
```
root@xxx:/# npm install iconv                                   
npm WARN package.json @0.0.2 No repository field.
npm WARN package.json @0.0.2 No README data
npm WARN package.json sparkl-io-kit@1.0.0 No description
npm WARN package.json sparkl-io-kit@1.0.0 No repository field.
npm WARN package.json sparkl-io-kit@1.0.0 No README data
npm http GET https://registry.npmjs.org/iconv
npm http 304 https://registry.npmjs.org/iconv
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> iconv@2.1.6 install /node_modules/iconv
> node-gyp rebuild

make: Entering directory `/node_modules/iconv/build'
  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
cc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make: *** [Release/obj.target/libiconv/deps/libiconv/lib/iconv.o] Error 4
make: Leaving directory `/node_modules/iconv/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.14.26-24.46.amzn1.x86_64
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /node_modules/iconv
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
```

**Comment by bnoordhuis** [comment]
> cc: internal compiler error: Killed (program cc1)

This has nothing to do with node-iconv.  You've either hit a real ICE (internal compiler error) or the process was running out of memory or hitting an ulimit.

**Comment by euvl** [comment]
thanks

**Comment by bnoordhuis** [comment]
No problem.  I'll close the issue.
