### ISSUE TITLE
v2.1.9 is Failing

### ISSUE THREAD

**Issue by kimb90** [bnoordhuis/node-iconv#124]
2.1.8 still works for me.

Here's the output.
2.1.9
```
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! iconv@2.1.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iconv@2.1.9 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.
```

**Comment by bnoordhuis** [comment]
Can you post the output of npm-debug.log?  It might be related to https://github.com/nodejs/nan/pull/404, which apparently only happens with the latest Xcode.

**Comment by kimb90** [comment]
```
Kimberlys-MacBook-Pro:dramafever klin$ ls
_gulpfile.js	dist		node_modules	src
config.json	gulpfile.js	package.json
Kimberlys-MacBook-Pro:dramafever klin$ npm install iconv@2.1.9
npm WARN package.json emails-df@1.0.0 No repository field.
npm WARN package.json emails-df@1.0.0 No README data

> iconv@2.1.9 install /Users/klin/DFHOME/sailthru-templates/dramafever/node_modules/iconv
> node-gyp rebuild

  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
  LIBTOOL-STATIC Release/iconv.a
  CXX(target) Release/obj.target/iconv/src/binding.o
In file included from ../src/binding.cc:18:
In file included from ../node_modules/nan/nan.h:2104:
../node_modules/nan/nan_weak.h:363:42: error: cannot create a non-constant
      pointer to member function
    v8::PersistentBase<T>::SetWeak(wcbd, wcbd->invoke);
                                         ^~~~~~~~~~~~
../node_modules/nan/nan_object_wrap.h:56:18: note: in instantiation of function
      template specialization 'Nan::Persistent<v8::Object,
      v8::NonCopyablePersistentTraits<v8::Object> >::SetWeak<Nan::ObjectWrap>'
      requested here
    persistent().SetWeak(this, WeakCallback, WeakCallbackType::kParameter);
                 ^
In file included from ../src/binding.cc:18:
In file included from ../node_modules/nan/nan.h:2104:
../node_modules/nan/nan_weak.h:378:42: error: cannot create a non-constant
      pointer to member function
    v8::PersistentBase<T>::SetWeak(wcbd, wcbd->invoke);
                                         ^~~~~~~~~~~~
../node_modules/nan/nan_weak.h:363:42: error: cannot create a non-constant
      pointer to member function
    v8::PersistentBase<T>::SetWeak(wcbd, wcbd->invoke);
                                         ^~~~~~~~~~~~
../src/binding.cc:91:16: note: in instantiation of function template
      specialization 'Nan::Persistent<v8::Object,
      v8::NonCopyablePersistentTraits<v8::Object> >::SetWeak<(anonymous
      namespace)::Iconv>' requested here
    persistent.SetWeak(iv, WeakCallback, Nan::WeakCallbackType::kParameter);
               ^
In file included from ../src/binding.cc:18:
In file included from ../node_modules/nan/nan.h:2104:
../node_modules/nan/nan_weak.h:378:42: error: cannot create a non-constant
      pointer to member function
    v8::PersistentBase<T>::SetWeak(wcbd, wcbd->invoke);
                                         ^~~~~~~~~~~~
4 errors generated.
make: *** [Release/obj.target/iconv/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/klin/DFHOME/sailthru-templates/dramafever/node_modules/iconv
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "iconv@2.1.9"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! iconv@2.1.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iconv@2.1.9 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/klin/DFHOME/sailthru-templates/dramafever/npm-debug.log
Kimberlys-MacBook-Pro:dramafever klin$ ls
_gulpfile.js	dist		node_modules	package.json
config.json	gulpfile.js	npm-debug.log	src
Kimberlys-MacBook-Pro:dramafever klin$ 
```

**Comment by bnoordhuis** [comment]
Right, same thing as https://github.com/nodejs/nan/pull/404.  I just landed that, when it's released, I'll update node-iconv as well.

**Comment by pedrofranceschi** [comment]
+1 this is breaking production!!

**Comment by pedrofranceschi** [comment]
@bnoordhuis could you please rollback until `nan` is fixed?

**Comment by kimb90** [comment]
Thanks @bnoordhuis!
