### ISSUE TITLE
Recent Build Issue Node 0.11.13

### ISSUE THREAD

**Issue by kennysmoothx** [bnoordhuis/node-iconv#127]
The latest node-iconv@2.1.10 appears to be failing to build:

```
> iconv@2.1.10 install /home/ubuntu/affiliate-site/node_modules/node-gettext/node_modules/iconv
> node-gyp rebuild

make: Entering directory `/home/ubuntu/affiliate-site/node_modules/node-gettext/node_modules/iconv/build'
  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
  AR(target) Release/obj.target/iconv.a
  COPY Release/iconv.a
  CXX(target) Release/obj.target/iconv/src/binding.o
In file included from ../src/binding.cc:18:0:
../node_modules/nan/nan.h: In function ‘void Nan::SetCounterFunction(v8::CounterLookupCallback)’:
../node_modules/nan/nan.h:449:32: error: ‘class v8::Isolate’ has no member named ‘SetCounterFunction’
../node_modules/nan/nan.h: In function ‘void Nan::SetCreateHistogramFunction(v8::CreateHistogramCallback)’:
../node_modules/nan/nan.h:454:32: error: ‘class v8::Isolate’ has no member named ‘SetCreateHistogramFunction’
../node_modules/nan/nan.h: In function ‘void Nan::SetAddHistogramSampleFunction(v8::AddHistogramSampleCallback)’:
../node_modules/nan/nan.h:459:32: error: ‘class v8::Isolate’ has no member named ‘SetAddHistogramSampleFunction’
../node_modules/nan/nan.h: In function ‘bool Nan::IdleNotification(int)’:
../node_modules/nan/nan.h:470:39: error: ‘class v8::Isolate’ has no member named ‘IdleNotification’
../node_modules/nan/nan.h: In function ‘void Nan::LowMemoryNotification()’:
../node_modules/nan/nan.h:475:32: error: ‘class v8::Isolate’ has no member named ‘LowMemoryNotification’
../node_modules/nan/nan.h: In function ‘void Nan::ContextDisposedNotification()’:
../node_modules/nan/nan.h:479:32: error: ‘class v8::Isolate’ has no member named ‘ContextDisposedNotification’
make: *** [Release/obj.target/iconv/src/binding.o] Error 1
make: Leaving directory `/home/ubuntu/affiliate-site/node_modules/node-gettext/node_modules/iconv/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/nvm/v0.11.13/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:12)
gyp ERR! System Linux 3.14.28-031428-generic
gyp ERR! command "node" "/home/ubuntu/nvm/v0.11.13/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/affiliate-site/node_modules/node-gettext/node_modules/iconv
gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Linux 3.14.28-031428-generic
npm ERR! argv "node" "/home/ubuntu/nvm/v0.11.13/bin/npm" "install"
npm ERR! node v0.11.13
npm ERR! npm  v2.12.0
npm ERR! code ELIFECYCLE

npm ERR! iconv@2.1.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iconv@2.1.10 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/affiliate-site/npm-debug.log

npm install returned exit code 1
```

May have happened with the recent updates to nan that were made.

**Comment by bnoordhuis** [comment]
The v0.11.x releases are not supported by nan anymore, they're unstable development releases that culminated in node.js v0.12 and io.js.  Use one of those.
