### ISSUE TITLE
libtool/linking error on OSX

### ISSUE THREAD

**Issue by wichert** [bnoordhuis/node-iconv#130]
Trying to install iconv on OSX 10.10 fails for me:

```
$ npm install iconv
\
> iconv@2.1.10 install /Users/wichert/Jzoo/website/node_modules/iconv
> node-gyp rebuild

  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
  LIBTOOL-STATIC Release/iconv.a
Usage: /opt/local/libexec/gnubin/libtool [OPTION]... [MODE-ARG]...
Try 'libtool --help' for more information.
libtool:   error: unrecognised option: '-static'
make: *** [Release/iconv.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/wichert/Jzoo/website/node_modules/iconv
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "install" "iconv"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.5
npm ERR! code ELIFECYCLE
```

**Comment by alexhgian** [comment]
Same issue here, I tried to install it on a vagrant vm with Ubuntu 12.04 and i get the same issue

**Comment by bnoordhuis** [comment]
That error means there is an incompatible libtool on the path.  Either remove it or rearrange the PATH environment variable so that `/usr/bin/libtool` comes first.

I'll close the issue, not a node-iconv bug.
