### ISSUE TITLE
Unable to install iconv on Ubuntu 12.04

### ISSUE THREAD

**Issue by kiyanwang** [bnoordhuis/node-iconv#131]
This start happening last night, it was working fine until then...

```
npm install iconv
npm http GET https://registry.npmjs.org/iconv
npm http 200 https://registry.npmjs.org/iconv
npm http GET https://registry.npmjs.org/iconv/-/iconv-2.1.10.tgz
npm http 200 https://registry.npmjs.org/iconv/-/iconv-2.1.10.tgz
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/nan/-/nan-2.0.9.tgz
npm http 200 https://registry.npmjs.org/nan/-/nan-2.0.9.tgz

> iconv@2.1.10 install /vagrant/talis/rl-app/node_modules/iconv
> node-gyp rebuild

gyp http GET http://nodejs.org/dist/v0.10.13/node-v0.10.13.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.13/node-v0.10.13.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack TypeError: Object 0.10.13 has no method 'slice'
gyp ERR! stack     at remove (/opt/node-v0.10.13-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/remove.js:37:21)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as remove] (/opt/node-v0.10.13-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at Gunzip.cb (/opt/node-v0.10.13-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:33:20)
gyp ERR! stack     at Gunzip.EventEmitter.emit (events.js:117:20)
gyp ERR! stack     at Zlib._binding.onerror (zlib.js:298:10)
gyp ERR! System Linux 3.2.0-23-generic
gyp ERR! command "node" "/opt/node-v0.10.13-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /vagrant/talis/rl-app/node_modules/iconv
gyp ERR! node -v v0.10.13
gyp ERR! node-gyp -v v0.10.2
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Please file an Issue:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
unbuild iconv@2.1.10
npm ERR! weird error 7
npm ERR! not ok code 0
```

Not sure how to fix this, any ideas?

**Comment by kiyanwang** [comment]
I also tried bumping up the version of node to (0.10.37)  and npm (1.4.28)

I still fails but with a slightly different error

```
> iconv@2.1.8 install /vagrant/talis/rl-app/node_modules/iconv
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: incorrect header check
gyp ERR! stack     at Zlib._binding.onerror (zlib.js:296:17)
gyp ERR! System Linux 3.2.0-23-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /vagrant/talis/rl-app/node_modules/iconv
gyp ERR! node -v v0.10.37
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

```

**Comment by kiyanwang** [comment]
its ok the problem was related to a website issue with node-gyp: https://github.com/nodejs/node-gyp/issues/721  it resolve itself. Apologies.
