### ISSUE TITLE
Node.js 5.0.0 on Mac install errors

### ISSUE THREAD

**Issue by JustFly1984** [bnoordhuis/node-iconv#137]
```
$ npm install

> iconv@2.1.11 install /******/node_modules/iconv
> node-gyp rebuild

  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
  LIBTOOL-STATIC Release/iconv.a
  CXX(target) Release/obj.target/iconv/src/binding.o
  SOLINK_MODULE(target) Release/iconv.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/iconv.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/************/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/************/.nvm/versions/node/v5.0.0/bin/node" "/************/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /************/TD/td_backend/node_modules/iconv
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```

**Comment by bnoordhuis** [comment]
> ld: library not found for -lgcc_s.10.5

That's not an issue with node-iconv.  Make sure your system is fully up to date, including xcode and the xcode command line tools.  Google around and you'll find that a lot of people have been getting that error.

**Comment by JustFly1984** [comment]
Thanx, I see now, that I do not have Xcode 7, only Xcode6.

2015-11-23 6:19 GMT+08:00 Ben Noordhuis <notifications@github.com>:
