### ISSUE TITLE
Error Converting UTF-32LE

### ISSUE THREAD

**Issue by PsyTae** [bnoordhuis/node-iconv#150]
I am working with a binary file that I am trying to parse through and store as variables using NodeJs. I have the file currently in a Buffer. This part of the file according to the requirements document is UTF-32 with a 4byte null character terminator.

```
41 00 00 00  55 00 00 00  54 00 00 00  4F 00 00 00 
31 00 00 00  45 00 00 00  30 00 00 00  33 00 00 00 
38 00 00 00  31 00 00 00  31 00 00 00  36 00 00 00 
00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00 
00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00 
00 00 00 00
```

When I try to use ICONV for the conversion all I keep getting is an error.

```
Iconv  		=	require('iconv').Iconv;
var convertUTF32 = new Iconv('UTF-32LE', 'UTF-8');

var string_UserName = convertUTF32.convert(data.slice(96, 179)).toString('utf8');
console.log('User Name: ' + string_UserName);
```

```
C:\nodeCode\node_modules\iconv\lib\iconv.js:145
          throw errnoException('EINVAL', 'Incomplete character sequence.');
          ^
Error: Incomplete character sequence.
    at errnoException (C:\nodeCode\node_modules\iconv\lib\iconv.js:169:13)
    at Object.convert (C:\nodeCode\node_modules\iconv\lib\iconv.js:145:17)
    at Iconv.convert (C:\nodeCode\node_modules\iconv\lib\iconv.js:59:12)
    at C:\nodeCode\metaProc.js:49:37
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
    at fs.js:312:11
    at nextTickCallbackWith0Args (node.js:456:9)
    at process._tickCallback (node.js:385:13)
```

How exactly would this need to be handled?

**Comment by bnoordhuis** [comment]
> data.slice(96, 179)

The length of the slice is not a multiple of 4, that's probably why you're getting that error.

**Comment by PsyTae** [comment]
96/0x60 is the "41"
179/0xB3 is the last "00"

You can see that it is in multiples of 4 in the HEX dump above.  If I do 176/0xB0 (start of last 4 bytes) or 180/0xB4 (start of next char) I get a different error.
```
C:\nodeCode\node_modules\iconv\lib\iconv.js:141
        throw errnoException('EILSEQ', 'Illegal character sequence.');
        ^
Error: Illegal character sequence.
    at errnoException (C:\nodeCode\node_modules\iconv\lib\iconv.js:169:13)
    at Object.convert (C:\nodeCode\node_modules\iconv\lib\iconv.js:141:15)
    at Iconv.convert (C:\nodeCode\node_modules\iconv\lib\iconv.js:59:12)
    at C:\nodeCode\metaProc.js:56:38
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
    at fs.js:312:11
    at nextTickCallbackWith0Args (node.js:456:9)
    at process._tickCallback (node.js:385:13)
```

179 is the last byte of the 4 byte char that starts at 176.
176, 177, 178, 179

Here is a hex dump of the first 255/FF characters

```
AF 03 00 00  D0 00 00 00  16 81 03 1E  0A 00 00 00 
00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00 
00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00 
00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00 
00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00 
00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00 
41 00 00 00  55 00 00 00  54 00 00 00  4F 00 00 00 
31 00 00 00  45 00 00 00  30 00 00 00  33 00 00 00 
38 00 00 00  31 00 00 00  31 00 00 00  36 00 00 00 
00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00 
00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00 
00 00 00 00  32 30 31 36  30 31 32 32  31 32 33 35 
34 32 30 30  30 30 30 00  00 00 00 00  00 00 00 00 
00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00 
00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00 
00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  
```

**Comment by PsyTae** [comment]
Finally figured out what I was doing wrong.  I didn't have the //TRANSLIT//IGNORE in there and had to shift the end index 1 as well since buffer.slice appears to be [Half-Closed Interval](http://www.mathwords.com/h/half_closed_interval.htm) [96, 180) and not [inclusive](http://www.mathwords.com/i/inclusive.htm) [96, 179] like I thought.

**Comment by bnoordhuis** [comment]
Glad it's solved.  I'll close the issue.
