### ISSUE TITLE
upgrade node 6.0, npm install ERROR "node-gyp rebuild"

### ISSUE THREAD

**Issue by why520crazy** [bnoordhuis/node-iconv#153]
upgrade node 6.0, npm install ERROR "node-gyp rebuild" 

run `npm install iconv` after `npm install node-gyp@3.3.1 -g`,
the error as

```
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
./Release/.deps/Release/obj.target/libiconv/deps/libiconv/lib/iconv.o.d.raw { dev: 16777220,
  mode: 33188,
  nlink: 1,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 63866192,
  size: 7111,
  blocks: 16,
  atime: 2016-04-27T05:30:06.000Z,
  mtime: 2016-04-27T05:30:06.000Z,
  ctime: 2016-04-27T05:30:06.000Z,
  birthtime: 2016-04-27T05:30:06.000Z }
  LIBTOOL-STATIC Release/iconv.a
  CXX(target) Release/obj.target/iconv/src/binding.o
In file included from ../src/binding.cc:18:
../node_modules/nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
4 errors generated.
make: *** [Release/obj.target/iconv/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/haifeng/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/haifeng/.nvm/versions/node/v6.0.0/bin/node" "/Users/haifeng/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/haifeng/IT/10_YC/projects/wt-pro-chat/node_modules/iconv
gyp ERR! node -v v6.0.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN wt-pro-chat@1.0.0 No description
npm WARN wt-pro-chat@1.0.0 No repository field.
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/haifeng/.nvm/versions/node/v6.0.0/bin/node" "/Users/haifeng/.nvm/versions/node/v6.0.0/bin/npm" "install" "iconv"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

```

**Comment by why520crazy** [comment]
perfect, thanks!!!

**Comment by YkmLo** [comment]
Hi, I am new at GitHub, so I don't understand how to read issues. I have open the link (Failed at the lame@1.2.3 install script 'node-gyp rebuild'. #62) but the people there just post "+1". I am having the same problem right now, how do I fix it?

**Comment by chrisli30** [comment]
Try npm install nan first. I had the same issue and below command solved it for me.

npm install nan@latest

nan@2.7.0 is actually installed

**Comment by andpor** [comment]
So what is the resolution here? I am getting same compile errors in npm install using node 6.9.1 ...

**Comment by why520crazy** [comment]
I solved it now use version `2.3.0`, can you try upgrade?

**Comment by andpor** [comment]
@why520crazy - how did you solve this exactly - can you provide steps?

**Comment by why520crazy** [comment]
@andpor I do not remember the details steps, but i'm sure i did not install `nan` ,  we use `"iconv": "^2.3.0"` and node `6.x` or `8.x` now, no errors in the installation.

**Comment by why520crazy** [comment]
@andpor you can try upgrade `node` to version `8.9.1` or `6.7.0`.

**Comment by why520crazy** [comment]
@andpor try `npm install` after delete `node_modules` folder.

**Comment by felipevignon** [comment]
> Try npm install nan first. I had the same issue and below command solved it for me.
> 
> npm install nan@latest
> 
> nan@2.7.0 is actually installed

This also worked for me even after windows-build-tools failed. I have no idea why, but it did the job.

Thanks!!
