### ISSUE TITLE
Ubuntu npm install error

### ISSUE THREAD

**Issue by kauegimenes** [bnoordhuis/node-iconv#159]
I keep getting this error message when using 

`npm install iconv`

```
make: Leaving directory `/home/user/project/node_modules/iconv/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-23-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/project/node_modules/iconv
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Linux 3.2.0-23-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "iconv"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
```

**Comment by bnoordhuis** [comment]
Can you post the full output?  You seem to have omitted the actual build error.

**Comment by westy92** [comment]
I'm trying to install inside a Docker container and I get an error as well.  I realize that 2.1.11 is not the latest version.
`Error: Cannot find module 'nan'`
Here's more information:

```
...
06-Jun-2016 20:35:57	npm info lifecycle iconv@2.1.11~install: iconv@2.1.11
06-Jun-2016 20:35:57	
06-Jun-2016 20:35:57	> iconv@2.1.11 install /node_modules/iconv
06-Jun-2016 20:35:57	> node-gyp rebuild
06-Jun-2016 20:35:57	
06-Jun-2016 20:35:57	gyp info it worked if it ends with ok
06-Jun-2016 20:35:57	gyp info using node-gyp@3.3.1
06-Jun-2016 20:35:57	gyp info using node@6.2.1 | linux | x64
06-Jun-2016 20:35:57	gyp http GET https://nodejs.org/download/release/v6.2.1/node-v6.2.1-headers.tar.gz
06-Jun-2016 20:35:57	gyp http 200 https://nodejs.org/download/release/v6.2.1/node-v6.2.1-headers.tar.gz
06-Jun-2016 20:35:58	gyp http GET https://nodejs.org/download/release/v6.2.1/SHASUMS256.txt
06-Jun-2016 20:35:58	gyp http 200 https://nodejs.org/download/release/v6.2.1/SHASUMS256.txt
06-Jun-2016 20:35:58	gyp info spawn /usr/bin/python2
06-Jun-2016 20:35:58	gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
06-Jun-2016 20:35:58	gyp info spawn args   'binding.gyp',
06-Jun-2016 20:35:58	gyp info spawn args   '-f',
06-Jun-2016 20:35:58	gyp info spawn args   'make',
06-Jun-2016 20:35:58	gyp info spawn args   '-I',
06-Jun-2016 20:35:58	gyp info spawn args   '/node_modules/iconv/build/config.gypi',
06-Jun-2016 20:35:58	gyp info spawn args   '-I',
06-Jun-2016 20:35:58	gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
06-Jun-2016 20:35:58	gyp info spawn args   '-I',
06-Jun-2016 20:35:58	gyp info spawn args   '/root/.node-gyp/6.2.1/include/node/common.gypi',
06-Jun-2016 20:35:58	gyp info spawn args   '-Dlibrary=shared_library',
06-Jun-2016 20:35:58	gyp info spawn args   '-Dvisibility=default',
06-Jun-2016 20:35:58	gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/6.2.1',
06-Jun-2016 20:35:58	gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
06-Jun-2016 20:35:58	gyp info spawn args   '-Dnode_lib_file=node.lib',
06-Jun-2016 20:35:58	gyp info spawn args   '-Dmodule_root_dir=/node_modules/iconv',
06-Jun-2016 20:35:58	gyp info spawn args   '--depth=.',
06-Jun-2016 20:35:58	gyp info spawn args   '--no-parallel',
06-Jun-2016 20:35:58	gyp info spawn args   '--generator-output',
06-Jun-2016 20:35:58	gyp info spawn args   'build',
06-Jun-2016 20:35:58	gyp info spawn args   '-Goutput_dir=.' ]
06-Jun-2016 20:35:58	module.js:442
06-Jun-2016 20:35:58	    throw err;
06-Jun-2016 20:35:58	    ^
06-Jun-2016 20:35:58	Error: Cannot find module 'nan'
06-Jun-2016 20:35:58	    at Function.Module._resolveFilename (module.js:440:15)
06-Jun-2016 20:35:58	    at Function.Module._load (module.js:388:25)
06-Jun-2016 20:35:58	    at Module.require (module.js:468:17)
06-Jun-2016 20:35:58	    at require (internal/module.js:20:19)
06-Jun-2016 20:35:58	    at [eval]:1:1
06-Jun-2016 20:35:58	    at Object.exports.runInThisContext (vm.js:54:17)
06-Jun-2016 20:35:58	    at Object.<anonymous> ([eval]-wrapper:6:22)
06-Jun-2016 20:35:58	    at Module._compile (module.js:541:32)
06-Jun-2016 20:35:58	    at node.js:333:29
06-Jun-2016 20:35:58	    at _combinedTickCallback (internal/process/next_tick.js:67:7)
06-Jun-2016 20:35:58	gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
06-Jun-2016 20:35:58	gyp ERR! configure error 
06-Jun-2016 20:35:58	gyp ERR! stack Error: `gyp` failed with exit code: 1
06-Jun-2016 20:35:58	gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
06-Jun-2016 20:35:58	gyp ERR! stack     at emitTwo (events.js:106:13)
06-Jun-2016 20:35:58	gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
06-Jun-2016 20:35:58	gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
06-Jun-2016 20:35:58	gyp ERR! System Linux 3.13.0-74-generic
06-Jun-2016 20:35:58	gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
06-Jun-2016 20:35:58	gyp ERR! cwd /node_modules/iconv
06-Jun-2016 20:35:58	gyp ERR! node -v v6.2.1
06-Jun-2016 20:35:58	gyp ERR! node-gyp -v v3.3.1
06-Jun-2016 20:35:58	gyp ERR! not ok 
06-Jun-2016 20:35:58	npm info lifecycle iconv@2.1.11~install: Failed to exec install script
```

**Comment by bnoordhuis** [comment]
@westy92 Can you file a new issue for that?  Hijacking existing issues is non bon ton.

**Comment by kauegimenes** [comment]
@bnoordhuis I was using Ubuntu 12, after updating to Ubuntu 14 the problem was solved.
