### ISSUE TITLE
npm install ERROR "node-gyp rebuild"

### ISSUE THREAD

**Issue by rtxrulez** [bnoordhuis/node-iconv#164]
`npm install iconv -g`

```1 verbose cli [ '/home/elena/.nvm/versions/node/v7.4.0/bin/node',
1 verbose cli   '/home/elena/.nvm/versions/node/v7.4.0/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   'iconv' ]
2 info using npm@4.0.5
3 info using node@v7.4.0


874 silly rollbackFailedOptional Finishing
875 silly runTopLevelLifecycles Finishing
876 silly install printInstalled
877 verbose stack Error: iconv@2.2.1 install: `node-gyp rebuild`
877 verbose stack Exit status 1
877 verbose stack     at EventEmitter.<anonymous> (/home/elena/.nvm/versions/node/v7.4.0/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
877 verbose stack     at emitTwo (events.js:106:13)
877 verbose stack     at EventEmitter.emit (events.js:191:7)
877 verbose stack     at ChildProcess.<anonymous> (/home/elena/.nvm/versions/node/v7.4.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
877 verbose stack     at emitTwo (events.js:106:13)
877 verbose stack     at ChildProcess.emit (events.js:191:7)
877 verbose stack     at maybeClose (internal/child_process.js:885:16)
877 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
878 verbose pkgid iconv@2.2.1
879 verbose cwd /home/elena/bin/test/node-vkbot
880 error Linux 4.4.0-36-generic
881 error argv "/home/elena/.nvm/versions/node/v7.4.0/bin/node" "/home/elena/.nvm/versions/node/v7.4.0/bin/npm" "i" "-g" "iconv"
882 error node v7.4.0
883 error npm  v4.0.5
884 error code ELIFECYCLE
885 error iconv@2.2.1 install: `node-gyp rebuild`
885 error Exit status 1
886 error Failed at the iconv@2.2.1 install script 'node-gyp rebuild'.
886 error Make sure you have the latest version of node.js and npm installed.
886 error If you do, this is most likely a problem with the iconv package,
886 error not with npm itself.
886 error Tell the author that this fails on your system:
886 error     node-gyp rebuild
886 error You can get information on how to open an issue for this project with:
886 error     npm bugs iconv
886 error Or if that isn't available, you can get their info via:
886 error     npm owner ls iconv
886 error There is likely additional logging output above.
887 verbose exit [ 1, true ]```

**Comment by bnoordhuis** [comment]
npm doesn't log the build output from node-gyp.  Can you run `node-gyp install iconv` and paste the output from the console?

**Comment by rtxrulez** [comment]
@bnoordhuis ```
elena@imgd1 ~/bin/webpack-test $ node-gyp install iconv
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.4.0 | linux | x64
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp http GET https://nodejs.org/dist/v7.4.0/node-v7.4.0-headers.tar.gz
gyp http 200 https://nodejs.org/dist/v7.4.0/node-v7.4.0-headers.tar.gz
gyp http GET https://nodejs.org/dist/v7.4.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/dist/v7.4.0/SHASUMS256.txt
7.4.0
gyp info ok 
```

**Comment by bnoordhuis** [comment]
Oops, I made a dumb typo; the command should be `npm install iconv`.  Sorry about that.

**Comment by GeekEdem** [comment]
The save issue with:

```
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Yurii\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Yurii\WebstormProjects\shipnext\node_modules\iconv
gyp ERR! node -v v7.2.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
```

**Comment by kauegimenes** [comment]
Same issue

OS: Windows 10 

```
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "iconv"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! iconv@2.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

**Comment by PsyTae** [comment]
same issue on
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3

```
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\NodeCode\Processor\node_modules\iconv
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN processor@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! iconv@2.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.2.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iconv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\NodeCode\Processor\npm-debug.log
```


Ran this just before the install..
npm install --global --production windows-build-tools
Finished with no errors

**Comment by zeg-io** [comment]
Same issue on Alpine Docker container

**Comment by zeg-io** [comment]
```
npm ERR! Linux 4.9.13-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--production"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! iconv@2.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.2.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iconv
```

**Comment by zeg-io** [comment]
Ok, turns out that _way_ up in the log it was failing because Apline didn't have `g++` installed.  I added it to the list and now it installs just fine

**Comment by amiraba** [comment]
Had the same issue...
Run the git bash or the command line console as an administrator when launching the npm install command
Worked for me ! ;)

**Comment by thenitai** [comment]
Run into the same issue. However solved it with (on Ubuntu 16.x):

```
apt install g++
```
and
```
npm install node-gyp
```
and finally a 
```
npm install iconv
```

Hope this helps.

**Comment by ccjon** [comment]
I am running npm install as root in the system, g++ is installed and on the path .... node-gyp installs without error and I am still getting this error node 4.7.0 and npm 2.15.1 on macosx and centos 6

**Comment by bnoordhuis** [comment]
@ccjon If you are using centos 6, your g++ is probably too old to work with node v4.x - it should be g++ >= 4.8.5.  There are a couple of ways to get a newer version but devtoolset is probably the easiest one.

I'm going to close this out.  If anyone still has trouble building, please file a new issue and include the full node-gyp output.

**Comment by gyofeel** [comment]
If you are using window 7 and have err log about Python 2.7

1. Download Python 2.7xx version with env variable
2. install node-gyp using npm : npm install node-gyp

After above, npm install iconv
In this way, I solved.

**Comment by NoumanDilshad** [comment]
I am having this issue when I run npm i iconv.
**These are the logs**.

```

C:\Users\Nouman Dilshad\Desktop\Projects\Unlock'd\Backend-Production>npm install iconv

> iconv@2.3.5 install C:\Users\Nouman Dilshad\Desktop\Projects\Unlock'd\Backend-Production\node_modules\iconv
> node-gyp rebuild


C:\Users\Nouman Dilshad\Desktop\Projects\Unlock'd\Backend-Production\node_modules\iconv>if not defined npm_config_node_gyp (node "C:\Users\Nouman Dilshad\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "%P\node_modules\node-gyp\bin\node-gyp.js" rebuild )
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'C:\Users\Nouman Dilshad\Desktop\Projects\Unlock'd\Backend-Production\node_modules\iconv\%P\node_modules\node-gyp\bin\node-gyp.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm WARN unlockd-backend@0.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iconv@2.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.3.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nouman Dilshad\AppData\Roaming\npm-cache\_logs\2019-10-17T08_11_49_648Z-debug.log
```
It will be great if someone could help. Thanks
