### ISSUE TITLE
Encoding WINDOWS-1252HTTP-EQUIVCONTENT-TYPE

### ISSUE THREAD

**Issue by GeekEdem** [bnoordhuis/node-iconv#165]
How can I add this encoding to library?)

`Error: Conversion from WINDOWS-1252HTTP-EQUIVCONTENT-TYPE to UTF-8//TRANSLIT//IGNORE is not supported.
    at new Iconv (node_modules/iconv/lib/iconv.js:51:11)
    at convertIconv (node_modules/encoding/lib/encoding.js:76:13)
    at convert (node_modules/encoding/lib/encoding.js:39:22)
    at Object.module.exports.decodeQuotedPrintable (node_modules/mimelib/lib/mimelib.js:99:54)
    at MailParser._finalizeContents (node_modules/mailparser/lib/mailparser.js:949:53)
    at MailParser._processStateBody (node_modules/mailparser/lib/mailparser.js:375:26)
    at MailParser._process (node_modules/mailparser/lib/mailparser.js:233:22)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
`

**Comment by bnoordhuis** [comment]
Is that a serious question?  You misspelled 'WINDOWS-1252'.

**Comment by GeekEdem** [comment]
@bnoordhuis Yes, this is serious, it is not misspelled. I receive this error when parsing emails. I understand, that it is not valid encoding, but this is not once issue. Several minutes ago I receive one more error with this:
`Error: Conversion from IBM437HTTP-EQUIVCONTENT-TYPE to UTF-8//TRANSLIT//IGNORE`

So how can you add in fixEncoding method replace string "HTTP-EQUIVCONTENT-TYPE" to ""?)

Thanks.

**Comment by bnoordhuis** [comment]
You don't, you fix up your inputs _before_ you pass them to node-iconv.  I'm going to close the issue because this is not a node-iconv bug in any way.
