### ISSUE TITLE
npm install fails with node v7.7.0

### ISSUE THREAD

**Issue by fixpunkt** [bnoordhuis/node-iconv#166]
`npm install` fails for my project:

```
# npm install

> fsevents@1.1.1 install xxx/node_modules/fsevents
> node install

[fsevents] Success: "xxx/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node" is installed via remote

> iconv@2.2.1 install xxx/node_modules/iconv
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/iconv/src/binding.o
In file included from ../src/binding.cc:18:
In file included from ../../nan/nan.h:47:
/Users/jannik/.node-gyp/7.7.0/include/node/node.h:44:10: fatal error: 'tracing/trace_event.h' file not found
#include "tracing/trace_event.h"
         ^
1 error generated.
make: *** [Release/obj.target/iconv/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jannik/.nvm/versions/node/v7.7.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/Users/jannik/.nvm/versions/node/v7.7.0/bin/node" "/Users/jannik/.nvm/versions/node/v7.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd xxx/node_modules/iconv
gyp ERR! node -v v7.7.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok

[...]



npm ERR! Darwin 16.4.0
npm ERR! argv "~/.nvm/versions/node/v7.7.0/bin/node" "~/.nvm/versions/node/v7.7.0/bin/npm" "install"
npm ERR! node v7.7.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! iconv@2.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.2.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iconv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     xxx/npm-debug.log
```
Here's the [npm-debug.log](https://github.com/bnoordhuis/node-iconv/files/810135/npm-debug.log.txt).

The output is for Mac OS, but I can reproduce the issue on Linux (Heroku).

**Comment by bnoordhuis** [comment]
Not a node-iconv issue but an issue with node.js v7.7.0, see nodejs/node#11628.
