### ISSUE TITLE
Install fails on Ubuntu 16.10

### ISSUE THREAD

**Issue by gitrago** [bnoordhuis/node-iconv#173]
After installing nom and node-gyp, I run

```
# npm install iconv

> iconv@2.2.3 install /apps/myapp/node_modules/iconv
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
/bin/sh: 1: node: Permission denied
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:304:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-1017-aws
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /apps/myapp/node_modules/iconv
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 4.4.0-1017-aws
npm ERR! argv "/root/.nvm/versions/node/v6.3.1/bin/node" "/root/.nvm/versions/node/v6.3.1/bin/npm" "install" "iconv"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! iconv@2.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iconv@2.2.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iconv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /apps/myapp/npm-debug.log
```

npm-debug.log:

```
552 verbose stack Error: iconv@2.2.3 install: `node-gyp rebuild`
552 verbose stack Exit status 1
552 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v6.3.1/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
552 verbose stack     at emitTwo (events.js:106:13)
552 verbose stack     at EventEmitter.emit (events.js:191:7)
552 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v6.3.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
552 verbose stack     at emitTwo (events.js:106:13)
552 verbose stack     at ChildProcess.emit (events.js:191:7)
552 verbose stack     at maybeClose (internal/child_process.js:852:16)
552 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
553 verbose pkgid iconv@2.2.3
554 verbose cwd /apps/myapp
555 error Linux 4.4.0-1017-aws
556 error argv "/root/.nvm/versions/node/v6.3.1/bin/node" "/root/.nvm/versions/node/v6.3.1/bin/npm" "install" "iconv"
557 error node v6.3.1
558 error npm  v3.10.3
559 error code ELIFECYCLE
560 error iconv@2.2.3 install: `node-gyp rebuild`
560 error Exit status 1
```

Please advise.

**Comment by gitrago** [comment]
Never mind this one, I had permission trouble on my `/root/.nvm/versions/node/v6.3.1/lib/node_modules` folder.
