### ISSUE TITLE
cant install iconv "cannot find fs.realpath"

### ISSUE THREAD

**Issue by dinesh124** [bnoordhuis/node-iconv#178]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchNamedPackageData nan
20 silly mapToRegistry name nan
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry uri https://registry.npmjs.org/nan
24 verbose request uri https://registry.npmjs.org/nan
25 verbose request no auth needed
26 info attempt registry request try #1 at 2:52:54 PM
27 verbose request id f75e82de050d6c66
28 verbose etag "5a3ad7f1-20c2f"
29 verbose lastModified Wed, 20 Dec 2017 21:36:49 GMT
30 http request GET https://registry.npmjs.org/nan
31 http 304 https://registry.npmjs.org/nan
32 verbose headers { date: 'Sat, 20 Jan 2018 09:22:45 GMT',
32 verbose headers   via: '1.1 varnish',
32 verbose headers   'cache-control': 'max-age=300',
32 verbose headers   etag: '"5a3ad7f1-20c2f"',
32 verbose headers   age: '7068',
32 verbose headers   connection: 'keep-alive',
32 verbose headers   'x-served-by': 'cache-ams4444-AMS',
32 verbose headers   'x-cache': 'HIT',
32 verbose headers   'x-cache-hits': '2',
32 verbose headers   'x-timer': 'S1516440166.953760,VS0,VE0',
32 verbose headers   vary: 'Accept-Encoding, Accept' }
33 silly get cb [ 304,
33 silly get   { date: 'Sat, 20 Jan 2018 09:22:45 GMT',
33 silly get     via: '1.1 varnish',
33 silly get     'cache-control': 'max-age=300',
33 silly get     etag: '"5a3ad7f1-20c2f"',
33 silly get     age: '7068',
33 silly get     connection: 'keep-alive',
33 silly get     'x-served-by': 'cache-ams4444-AMS',
33 silly get     'x-cache': 'HIT',
33 silly get     'x-cache-hits': '2',
33 silly get     'x-timer': 'S1516440166.953760,VS0,VE0',
33 silly get     vary: 'Accept-Encoding, Accept' } ]
34 verbose etag https://registry.npmjs.org/nan from cache
35 verbose get saving nan to C:\Users\ns\AppData\Roaming\npm-cache\registry.npmjs.org\nan\.cache.json
36 silly resolveWithNewModule nan@2.8.0 checking installable status
37 silly cache add args [ 'nan@^2.3.5', null ]
38 verbose cache add spec nan@^2.3.5
39 silly cache add parsed spec Result {
39 silly cache add   raw: 'nan@^2.3.5',
39 silly cache add   scope: null,
39 silly cache add   name: 'nan',
39 silly cache add   rawSpec: '^2.3.5',
39 silly cache add   spec: '>=2.3.5 <3.0.0',
39 silly cache add   type: 'range' }
40 silly addNamed nan@>=2.3.5 <3.0.0
41 verbose addNamed ">=2.3.5 <3.0.0" is a valid semver range for nan
42 silly addNameRange { name: 'nan', range: '>=2.3.5 <3.0.0', hasData: false }
43 silly mapToRegistry name nan
44 silly mapToRegistry using default registry
45 silly mapToRegistry registry https://registry.npmjs.org/
46 silly mapToRegistry uri https://registry.npmjs.org/nan
47 verbose addNameRange registry:https://registry.npmjs.org/nan not in flight; fetching
48 verbose get https://registry.npmjs.org/nan not expired, no request
49 silly addNameRange number 2 { name: 'nan', range: '>=2.3.5 <3.0.0', hasData: true }
50 silly addNameRange versions [ 'nan',
50 silly addNameRange   [ '0.3.0-wip',
50 silly addNameRange     '0.3.0-wip2',
50 silly addNameRange     '0.3.0',
50 silly addNameRange     '0.3.1',
50 silly addNameRange     '0.3.2',
50 silly addNameRange     '0.4.0',
50 silly addNameRange     '0.4.1',
50 silly addNameRange     '0.4.2',
50 silly addNameRange     '0.4.3',
50 silly addNameRange     '0.4.4',
50 silly addNameRange     '0.5.0',
50 silly addNameRange     '0.5.1',
50 silly addNameRange     '0.5.2',
50 silly addNameRange     '0.6.0',
50 silly addNameRange     '0.7.0',
50 silly addNameRange     '0.7.1',
50 silly addNameRange     '0.8.0',
50 silly addNameRange     '1.0.0',
50 silly addNameRange     '1.1.0',
50 silly addNameRange     '1.1.1',
50 silly addNameRange     '1.1.2',
50 silly addNameRange     '1.2.0',
50 silly addNameRange     '1.3.0',
50 silly addNameRange     '1.4.0',
50 silly addNameRange     '1.4.1',
50 silly addNameRange     '1.5.0',
50 silly addNameRange     '1.4.2',
50 silly addNameRange     '1.4.3',
50 silly addNameRange     '1.5.1',
50 silly addNameRange     '1.5.2',
50 silly addNameRange     '1.6.0',
50 silly addNameRange     '1.5.3',
50 silly addNameRange     '1.6.1',
50 silly addNameRange     '1.6.2',
50 silly addNameRange     '1.7.0',
50 silly addNameRange     '1.8.0',
50 silly addNameRange     '1.8.1',
50 silly addNameRange     '1.8.2',
50 silly addNameRange     '1.8.3',
50 silly addNameRange     '1.8.4',
50 silly addNameRange     '1.9.0',
50 silly addNameRange     '2.0.0',
50 silly addNameRange     '2.0.1',
50 silly addNameRange     '2.0.2',
50 silly addNameRange     '2.0.3',
50 silly addNameRange     '2.0.4',
50 silly addNameRange     '2.0.5',
50 silly addNameRange     '2.0.6',
50 silly addNameRange     '2.0.7',
50 silly addNameRange     '2.0.8',
50 silly addNameRange     '2.0.9',
50 silly addNameRange     '2.1.0',
50 silly addNameRange     '2.2.0',
50 silly addNameRange     '2.2.1',
50 silly addNameRange     '2.3.0',
50 silly addNameRange     '2.3.1',
50 silly addNameRange     '2.3.2',
50 silly addNameRange     '2.3.3',
50 silly addNameRange     '2.3.4',
50 silly addNameRange     '2.3.5',
50 silly addNameRange     '2.4.0',
50 silly addNameRange     '2.5.0',
50 silly addNameRange     '2.5.1',
50 silly addNameRange     '2.6.0',
50 silly addNameRange     '2.6.1',
50 silly addNameRange     '2.6.2',
50 silly addNameRange     '2.7.0',
50 silly addNameRange     '2.8.0' ] ]
51 silly addNamed nan@2.8.0
52 verbose addNamed "2.8.0" is a plain semver version for nan
53 silly cache afterAdd nan@2.8.0
54 verbose afterAdd C:\Users\ns\AppData\Roaming\npm-cache\nan\2.8.0\package\package.json not in flight; writing
55 verbose afterAdd C:\Users\ns\AppData\Roaming\npm-cache\nan\2.8.0\package\package.json written
56 silly loadAllDepsIntoIdealTree Finishing
57 silly idealTree:prePrune iconv@2.3.0
57 silly idealTree:prePrune └── nan@2.8.0
58 silly loadIdealTree Finishing
59 silly currentTree iconv@2.3.0
60 silly idealTree iconv@2.3.0
60 silly idealTree └── nan@2.8.0
61 silly generateActionsToTake Starting
62 silly install generateActionsToTake
63 silly generateActionsToTake Finishing
64 silly diffTrees action count 1
65 silly diffTrees add nan@2.8.0
66 silly decomposeActions action count 8
67 silly decomposeActions fetch nan@2.8.0
68 silly decomposeActions extract nan@2.8.0
69 silly decomposeActions preinstall nan@2.8.0
70 silly decomposeActions build nan@2.8.0
71 silly decomposeActions install nan@2.8.0
72 silly decomposeActions postinstall nan@2.8.0
73 silly decomposeActions test nan@2.8.0
74 silly decomposeActions finalize nan@2.8.0
75 silly executeActions Starting
76 silly install executeActions
77 silly doSerial global-install 0
78 silly doParallel fetch 1
79 verbose lock using C:\Users\ns\AppData\Roaming\npm-cache\_locks\staging-bafbc3d030a04031.lock for C:\tracking-masters\node-iconv\node_modules\.staging
80 silly doParallel extract 1
81 silly extract nan
82 verbose unbuild node_modules\.staging\nan-050bb456302fce39fc488f9ea76fd180
83 silly gentlyRm C:\tracking-masters\node-iconv\node_modules\.staging\nan-050bb456302fce39fc488f9ea76fd180 is being purged from base C:\tracking-masters\node-iconv
84 verbose gentlyRm don't care about contents; nuking C:\tracking-masters\node-iconv\node_modules\.staging\nan-050bb456302fce39fc488f9ea76fd180
85 verbose tar unpack C:\Users\ns\AppData\Roaming\npm-cache\nan\2.8.0\package.tgz
86 verbose tar unpacking to C:\tracking-masters\node-iconv\node_modules\.staging\nan-050bb456302fce39fc488f9ea76fd180
87 silly gentlyRm C:\tracking-masters\node-iconv\node_modules\.staging\nan-050bb456302fce39fc488f9ea76fd180 is being purged
88 verbose gentlyRm don't care about contents; nuking C:\tracking-masters\node-iconv\node_modules\.staging\nan-050bb456302fce39fc488f9ea76fd180
89 silly gunzTarPerm modes [ '777', '666' ]
90 silly gunzTarPerm extractEntry package.json
91 silly gunzTarPerm modified mode [ 'package.json', 436, 438 ]
92 silly gunzTarPerm extractEntry README.md
93 silly gunzTarPerm modified mode [ 'README.md', 436, 438 ]
94 silly gunzTarPerm extractEntry include_dirs.js
95 silly gunzTarPerm modified mode [ 'include_dirs.js', 436, 438 ]
96 silly gunzTarPerm extractEntry nan_converters_43_inl.h
97 silly gunzTarPerm modified mode [ 'nan_converters_43_inl.h', 436, 438 ]
98 silly gunzTarPerm extractEntry LICENSE.md
99 silly gunzTarPerm modified mode [ 'LICENSE.md', 436, 438 ]
100 silly gunzTarPerm extractEntry doc/new.md
101 silly gunzTarPerm modified mode [ 'doc/new.md', 436, 438 ]
102 silly gunzTarPerm extractEntry doc/asyncworker.md
103 silly gunzTarPerm modified mode [ 'doc/asyncworker.md', 436, 438 ]
104 silly gunzTarPerm extractEntry doc/callback.md
105 silly gunzTarPerm modified mode [ 'doc/callback.md', 436, 438 ]
106 silly gunzTarPerm extractEntry doc/converters.md
107 silly gunzTarPerm modified mode [ 'doc/converters.md', 436, 438 ]
108 silly gunzTarPerm extractEntry doc/errors.md
109 silly gunzTarPerm modified mode [ 'doc/errors.md', 436, 438 ]
110 silly gunzTarPerm extractEntry doc/json.md
111 silly gunzTarPerm modified mode [ 'doc/json.md', 436, 438 ]
112 silly gunzTarPerm extractEntry doc/maybe_types.md
113 silly gunzTarPerm modified mode [ 'doc/maybe_types.md', 436, 438 ]
114 silly gunzTarPerm extractEntry doc/methods.md
115 silly gunzTarPerm modified mode [ 'doc/methods.md', 436, 438 ]
116 silly gunzTarPerm extractEntry doc/buffers.md
117 silly gunzTarPerm modified mode [ 'doc/buffers.md', 436, 438 ]
118 silly gunzTarPerm extractEntry doc/node_misc.md
119 silly gunzTarPerm modified mode [ 'doc/node_misc.md', 436, 438 ]
120 silly gunzTarPerm extractEntry doc/object_wrappers.md
121 silly gunzTarPerm modified mode [ 'doc/object_wrappers.md', 436, 438 ]
122 silly gunzTarPerm extractEntry doc/persistent.md
123 silly gunzTarPerm modified mode [ 'doc/persistent.md', 436, 438 ]
124 silly gunzTarPerm extractEntry doc/scopes.md
125 silly gunzTarPerm modified mode [ 'doc/scopes.md', 436, 438 ]
126 silly gunzTarPerm extractEntry doc/script.md
127 silly gunzTarPerm modified mode [ 'doc/script.md', 436, 438 ]
128 silly gunzTarPerm extractEntry doc/string_bytes.md
129 silly gunzTarPerm modified mode [ 'doc/string_bytes.md', 436, 438 ]
130 silly gunzTarPerm extractEntry doc/v8_internals.md
131 silly gunzTarPerm modified mode [ 'doc/v8_internals.md', 436, 438 ]
132 silly gunzTarPerm extractEntry doc/v8_misc.md
133 silly gunzTarPerm modified mode [ 'doc/v8_misc.md', 436, 438 ]
134 silly gunzTarPerm extractEntry nan.h
135 silly gunzTarPerm modified mode [ 'nan.h', 436, 438 ]
136 silly gunzTarPerm extractEntry nan_callbacks.h
137 silly gunzTarPerm modified mode [ 'nan_callbacks.h', 436, 438 ]
138 silly gunzTarPerm extractEntry nan_callbacks_12_inl.h
139 silly gunzTarPerm modified mode [ 'nan_callbacks_12_inl.h', 436, 438 ]
140 silly gunzTarPerm extractEntry nan_callbacks_pre_12_inl.h
141 silly gunzTarPerm modified mode [ 'nan_callbacks_pre_12_inl.h', 436, 438 ]
142 silly gunzTarPerm extractEntry nan_converters.h
143 silly gunzTarPerm modified mode [ 'nan_converters.h', 436, 438 ]
144 silly gunzTarPerm extractEntry nan_converters_pre_43_inl.h
145 silly gunzTarPerm modified mode [ 'nan_converters_pre_43_inl.h', 436, 438 ]
146 silly gunzTarPerm extractEntry nan_implementation_12_inl.h
147 silly gunzTarPerm modified mode [ 'nan_implementation_12_inl.h', 436, 438 ]
148 silly gunzTarPerm extractEntry nan_implementation_pre_12_inl.h
149 silly gunzTarPerm modified mode [ 'nan_implementation_pre_12_inl.h', 436, 438 ]
150 silly gunzTarPerm extractEntry nan_json.h
151 silly gunzTarPerm modified mode [ 'nan_json.h', 436, 438 ]
152 silly gunzTarPerm extractEntry nan_maybe_43_inl.h
153 silly gunzTarPerm modified mode [ 'nan_maybe_43_inl.h', 436, 438 ]
154 silly gunzTarPerm extractEntry nan_maybe_pre_43_inl.h
155 silly gunzTarPerm modified mode [ 'nan_maybe_pre_43_inl.h', 436, 438 ]
156 silly gunzTarPerm extractEntry nan_new.h
157 silly gunzTarPerm modified mode [ 'nan_new.h', 436, 438 ]
158 silly gunzTarPerm extractEntry nan_object_wrap.h
159 silly gunzTarPerm modified mode [ 'nan_object_wrap.h', 436, 438 ]
160 silly gunzTarPerm extractEntry nan_persistent_12_inl.h
161 silly gunzTarPerm modified mode [ 'nan_persistent_12_inl.h', 436, 438 ]
162 silly gunzTarPerm extractEntry nan_persistent_pre_12_inl.h
163 silly gunzTarPerm modified mode [ 'nan_persistent_pre_12_inl.h', 436, 438 ]
164 silly gunzTarPerm extractEntry nan_private.h
165 silly gunzTarPerm modified mode [ 'nan_private.h', 436, 438 ]
166 silly gunzTarPerm extractEntry nan_string_bytes.h
167 silly gunzTarPerm modified mode [ 'nan_string_bytes.h', 436, 438 ]
168 silly gunzTarPerm extractEntry nan_typedarray_contents.h
169 silly gunzTarPerm modified mode [ 'nan_typedarray_contents.h', 436, 438 ]
170 silly gunzTarPerm extractEntry nan_weak.h
171 silly gunzTarPerm modified mode [ 'nan_weak.h', 436, 438 ]
172 silly gunzTarPerm extractEntry CHANGELOG.md
173 silly gunzTarPerm modified mode [ 'CHANGELOG.md', 436, 438 ]
174 silly gunzTarPerm extractEntry tools/package.json
175 silly gunzTarPerm modified mode [ 'tools/package.json', 436, 438 ]
176 silly gunzTarPerm extractEntry tools/README.md
177 silly gunzTarPerm modified mode [ 'tools/README.md', 436, 438 ]
178 silly gunzTarPerm extractEntry tools/1to2.js
179 silly gunzTarPerm modified mode [ 'tools/1to2.js', 509, 511 ]
180 silly doParallel preinstall 1
181 silly preinstall nan C:\tracking-masters\node-iconv\node_modules\.staging\nan-050bb456302fce39fc488f9ea76fd180
182 info lifecycle nan@2.8.0~preinstall: nan@2.8.0
183 silly lifecycle nan@2.8.0~preinstall: no script for preinstall, continuing
184 silly doReverseSerial remove 0
185 silly doSerial move 0
186 silly doSerial finalize 1
187 silly finalize C:\tracking-masters\node-iconv\node_modules\nan
188 silly doSerial build 1
189 silly build nan
190 info linkStuff nan@2.8.0
191 silly linkStuff nan@2.8.0 has C:\tracking-masters\node-iconv\node_modules as its parent node_modules
192 verbose linkBins nan@2.8.0
193 verbose linkMans nan@2.8.0
194 verbose rebuildBundles nan@2.8.0
195 silly doSerial global-link 0
196 silly doParallel update-linked 0
197 silly doSerial install 1
198 silly install nan C:\tracking-masters\node-iconv\node_modules\.staging\nan-050bb456302fce39fc488f9ea76fd180
199 info lifecycle nan@2.8.0~install: nan@2.8.0
200 silly lifecycle nan@2.8.0~install: no script for install, continuing
201 silly doSerial postinstall 1
202 silly postinstall nan C:\tracking-masters\node-iconv\node_modules\.staging\nan-050bb456302fce39fc488f9ea76fd180
203 info lifecycle nan@2.8.0~postinstall: nan@2.8.0
204 silly lifecycle nan@2.8.0~postinstall: no script for postinstall, continuing
205 verbose unlock done using C:\Users\ns\AppData\Roaming\npm-cache\_locks\staging-bafbc3d030a04031.lock for C:\tracking-masters\node-iconv\node_modules\.staging
206 silly executeActions Finishing
207 silly rollbackFailedOptional Starting
208 silly rollbackFailedOptional Finishing
209 silly runTopLevelLifecycles Starting
210 silly install runTopLevelLifecycles
211 silly preinstall iconv C:\tracking-masters\node-iconv\iconv-c68c4b5ec986979a3723a2328e081749
212 info lifecycle iconv@2.3.0~preinstall: iconv@2.3.0
213 silly lifecycle iconv@2.3.0~preinstall: no script for preinstall, continuing
214 silly build iconv
215 info linkStuff iconv@2.3.0
216 silly linkStuff iconv@2.3.0 has C:\tracking-masters as its parent node_modules
217 verbose linkBins iconv@2.3.0
218 verbose linkMans iconv@2.3.0
219 verbose rebuildBundles iconv@2.3.0
220 verbose rebuildBundles [ 'nan' ]
221 silly install iconv C:\tracking-masters\node-iconv\iconv-c68c4b5ec986979a3723a2328e081749
222 info lifecycle iconv@2.3.0~install: iconv@2.3.0
223 verbose lifecycle iconv@2.3.0~install: unsafe-perm in lifecycle true
224 verbose lifecycle iconv@2.3.0~install: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\tracking-masters\node-iconv\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\NVIDIA Corporation\PhysX\Common;C:\Program Files\PC Connectivity Solution\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Windows Kits\8.0\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\GtkSharp\2.12\bin;C:\Program Files\TortoiseGit\bin;E:\dinesh\java eclipse\jdk\bin;C:\adb;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\NVIDIA Corporation\PhysX\Common;C:\Program Files\PC Connectivity Solution\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Windows Kits\8.0\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\GtkSharp\2.12\bin;C:\Program Files\TortoiseGit\bin;E:\dinesh\java eclipse\jdk\bin;C:\adb;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\NVIDIA Corporation\PhysX\Common;C:\Program Files\PC Connectivity Solution\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Windows Kits\8.0\Windows Performance Toolkit\;C:\Python27;C:\Program F
225 verbose lifecycle iconv@2.3.0~install: CWD: C:\tracking-masters\node-iconv
226 silly lifecycle iconv@2.3.0~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
227 silly lifecycle iconv@2.3.0~install: Returned: code: 7  signal: null
228 info lifecycle iconv@2.3.0~install: Failed to exec install script
229 verbose stack Error: iconv@2.3.0 install: `node-gyp rebuild`
229 verbose stack Exit status 7
229 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:233:16)
229 verbose stack     at emitTwo (events.js:87:13)
229 verbose stack     at EventEmitter.emit (events.js:172:7)
229 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
229 verbose stack     at emitTwo (events.js:87:13)
229 verbose stack     at ChildProcess.emit (events.js:172:7)
229 verbose stack     at maybeClose (internal/child_process.js:818:16)
229 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
230 verbose pkgid iconv@2.3.0
231 verbose cwd C:\tracking-masters\node-iconv
232 error Windows_NT 6.1.7600
233 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
234 error node v5.0.0
235 error npm  v3.3.6
236 error code ELIFECYCLE
237 error iconv@2.3.0 install: `node-gyp rebuild`
237 error Exit status 7
238 error Failed at the iconv@2.3.0 install script 'node-gyp rebuild'.
238 error This is most likely a problem with the iconv package,
238 error not with npm itself.
238 error Tell the author that this fails on your system:
238 error     node-gyp rebuild
238 error You can get their info via:
238 error     npm owner ls iconv
238 error There is likely additional logging output above.
239 verbose exit [ 1, true ]
```

cannot install iconv please help
this is the debug info

**Comment by bnoordhuis** [comment]
"cannot find fs.realpath" is not mentioned at all in the logs...

The actual error is probably on your console (npm doesn't log those) but it's probably that you either need to `npm install -g windows-build-tools` or upgrade to a version of node.js that is still supported.

**Comment by dinesh124** [comment]
i have installed the windows build tools yet i am getting the same error
![capture](https://user-images.githubusercontent.com/35265617/35193549-3c787302-feca-11e7-986d-95b3c44f5b62.PNG)
![capture1](https://user-images.githubusercontent.com/35265617/35193550-3ccc26a0-feca-11e7-8b56-0415c853e2cb.PNG)
![capture2](https://user-images.githubusercontent.com/35265617/35193551-3d197cfc-feca-11e7-86a6-96b5df41656d.PNG)

these are the screenshots i took after the installation fs.realpath error is shown here

**Comment by bnoordhuis** [comment]
Looks like you have a borked npm or node-gyp installation.  npm@3.3.6 ships with node-gyp@3.0.3, not 3.6.2.
