### ISSUE TITLE
Install fails on Windows 10

### ISSUE THREAD

**Issue by flangellotti** [bnoordhuis/node-iconv#180]
```
D:\Users\Francesco\Documents\Sviluppo\NodeJs\TelegramBot\node_modules\iconv>if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\Program Files\n
odejs\node_modules\npm\node_modules\npm-lifecycle\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Compilazione dei progetti nella soluzione uno alla volta. Per abilitare la compilazione parallela, aggiungere l'opzione "/m".
  binding.cc
  win_delay_load_hook.cc
  iconv.c
  localcharset.c
LINK : fatal error LNK1104: cannot open file 'libucrt.lib' [D:\Users\Francesco\Documents\Sviluppo\NodeJs\TelegramBot\node_modules\iconv\build\iconv.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\npm-lifecycle\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Users\Francesco\Documents\Sviluppo\NodeJs\TelegramBot\node_modules\iconv
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN telegrambot@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iconv@2.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Francesco\AppData\Roaming\npm-cache\_logs\2018-04-06T14_38_23_320Z-debug.log
```

[LOG](https://pastebin.com/esgSmtNR)

**Comment by flangellotti** [comment]
How i can fix this?

**Comment by bnoordhuis** [comment]
Google that error, you'll find some blog posts and github issues with more info.
