### ISSUE TITLE
Does this package depend on Python?

### ISSUE THREAD

**Issue by LongTengDao** [bnoordhuis/node-iconv#201]
```cmd
D:\ProjectDirectory>npm install iconv

> iconv@2.3.4 install D:\ProjectDirectory\node_modules\iconv
> node-gyp rebuild


D:\ProjectDirectory\node_modules\iconv>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "/Python27/python.exe", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\ProjectDirectory\node_modules\iconv
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'D:\ProjectDirectory\package.json'
npm WARN ProjectDirectory No description
npm WARN ProjectDirectory No repository field.
npm WARN ProjectDirectory No README data
npm WARN ProjectDirectory No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iconv@2.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.3.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\UserName\AppData\Roaming\npm-cache\_logs\2019-06-09T12_50_40_714Z-debug.log
```

**Comment by bnoordhuis** [comment]
Indirectly. It depends on [node-gyp](https://github.com/nodejs/node-gyp/pulls), the standard build tool for native modules, and node-gyp depends on python 2.7.
